/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/plane_main.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.engine001_Cylinder013.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.aileron001_Cube013.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.box_1001_Cube012.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wheel003_Cylinder012.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.hydraolic003_Cube011.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.box_2003_Plane004.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.gear_1003_Cylinder011.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.fuselage001_Cube010.geometry} material={materials['texture_texture.png']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.antenna001_Cube009.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wheel_001001_Cylinder010.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.gear_1_001001_Cylinder009.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.hydraolic001_Cube008.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.box_2002_Plane003.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wheel002_Cylinder008.geometry} material={materials.texture} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.gear_1002_Cylinder007.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/plane_main.gltf')
